# Site settings
theme: adriana-guzman/my-own-jekyll-theme
title: Adriana 2
description: "A blog for Adriana 2"

remote_theme: https://github.com/adriana-guzman/my-own-jekyll-theme
#remote_theme: KingFelix/emerald

plugins:
  - jekyll-remote-theme
